protocol: udp # <-- change this to the protocol you want to use (tcp or web)
packaging_type: msgpack # <-- change this to the packaging method you want to use (json, msgpack or pickle)
test_file_name: episode0.hdf5
is_jpeg: true
